# automatically generated by the FlatBuffers compiler, do not modify

# namespace: types

import flatbuffers

class Level(object):
    __slots__ = ['_tab']

    # Level
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Level
    def Price(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Level
    def Qty(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))

def CreateLevel(builder, Price, Qty):
    builder.Prep(4, 8)
    builder.PrependFloat32(Qty)
    builder.PrependFloat32(Price)
    return builder.Offset()
