// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package types

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Levels struct {
	_tab flatbuffers.Table
}

func GetRootAsLevels(buf []byte, offset flatbuffers.UOffsetT) *Levels {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Levels{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Levels) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Levels) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Levels) Data(obj *Level, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 8
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Levels) DataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func LevelsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func LevelsAddData(builder *flatbuffers.Builder, Data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(Data), 0)
}
func LevelsStartDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 4)
}
func LevelsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
