// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package types

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Level struct {
	_tab flatbuffers.Struct
}

func (rcv *Level) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Level) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *Level) Price() float32 {
	return rcv._tab.GetFloat32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *Level) MutatePrice(n float32) bool {
	return rcv._tab.MutateFloat32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *Level) Qty() float32 {
	return rcv._tab.GetFloat32(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *Level) MutateQty(n float32) bool {
	return rcv._tab.MutateFloat32(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func CreateLevel(builder *flatbuffers.Builder, Price float32, Qty float32) flatbuffers.UOffsetT {
	builder.Prep(4, 8)
	builder.PrependFloat32(Qty)
	builder.PrependFloat32(Price)
	return builder.Offset()
}
